"""add avatar and social links to users

Revision ID: 410fe785c996
Revises: 1b9531df0310
Create Date: 2026-08-10 22:31:55.130455

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '410fe785c996'
down_revision = '1b9531df0310'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('facebook_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('instagram_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('twitter_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'twitter_url')
    op.drop_column('users', 'instagram_url')
    op.drop_column('users', 'facebook_url')
    op.drop_column('users', 'avatar_key')
    # ### end Alembic commands ###
