"""add organizer role

Revision ID: 5846d49976df
Revises: f41478881d7e
Create Date: 2026-08-17 22:37:13.204975

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '5846d49976df'
down_revision = 'f41478881d7e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Postgres enum value additions can't run inside the same transaction that uses
    # the new value, but adding them alone in this migration's transaction is fine
    # (same approach as d4a96917e1f4_add_moderator_role.py).
    op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'ORGANIZER'")
    op.execute("ALTER TYPE eventstatus ADD VALUE IF NOT EXISTS 'PENDING_REVIEW'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizer_applications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='organizerapplicationstatus'), nullable=False),
    sa.Column('legal_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_document_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_document_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_document_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('organization_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizer_applications_status'), 'organizer_applications', ['status'], unique=False)
    op.create_index(op.f('ix_organizer_applications_user_id'), 'organizer_applications', ['user_id'], unique=False)

    # created_by added nullable, backfilled from the parent event's owner, then locked
    # down — existing rows predate this column so a straight NOT NULL add would fail.
    op.add_column('prizes', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.execute(
        "UPDATE prizes SET created_by = events.created_by FROM events WHERE events.id = prizes.event_id"
    )
    op.alter_column('prizes', 'created_by', nullable=False)
    op.create_foreign_key(None, 'prizes', 'users', ['created_by'], ['id'])

    op.add_column('stages', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.execute(
        "UPDATE stages SET created_by = events.created_by FROM events WHERE events.id = stages.event_id"
    )
    op.alter_column('stages', 'created_by', nullable=False)
    op.create_foreign_key(None, 'stages', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # Postgres has no direct "remove enum value" operation for the userrole/eventstatus
    # additions made in upgrade() — same limitation as d4a96917e1f4_add_moderator_role.py.
    # Left as a no-op; reverting this on a DB with ORGANIZER users or PENDING_REVIEW
    # events is unsafe anyway.

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stages', type_='foreignkey')
    op.drop_column('stages', 'created_by')
    op.drop_constraint(None, 'prizes', type_='foreignkey')
    op.drop_column('prizes', 'created_by')
    op.drop_index(op.f('ix_organizer_applications_user_id'), table_name='organizer_applications')
    op.drop_index(op.f('ix_organizer_applications_status'), table_name='organizer_applications')
    op.drop_table('organizer_applications')
    # ### end Alembic commands ###
