"""add judge scoring and winning mode

Revision ID: 820460178809
Revises: 5846d49976df
Create Date: 2026-08-18 10:49:05.350510

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '820460178809'
down_revision = '5846d49976df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_judges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_event_judge_event_user')
    )
    op.create_index(op.f('ix_event_judges_event_id'), 'event_judges', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_judges_user_id'), 'event_judges', ['user_id'], unique=False)
    op.create_table('judge_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('judge_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['judge_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'judge_id', name='uq_judge_score_submission_judge')
    )
    op.create_index(op.f('ix_judge_scores_judge_id'), 'judge_scores', ['judge_id'], unique=False)
    op.create_index(op.f('ix_judge_scores_submission_id'), 'judge_scores', ['submission_id'], unique=False)

    # Added nullable, backfilled to the existing default, then locked down — existing events
    # predate this column so a straight NOT NULL add would fail (same pattern as
    # 5846d49976df's stages/prizes.created_by backfill).
    winning_mode_enum = sa.Enum('AUDIENCE_VOTE', 'JUDGE_SCORE', 'ADMIN_CURATED', name='winningmode')
    winning_mode_enum.create(op.get_bind())
    op.add_column('events', sa.Column('winning_mode', winning_mode_enum, nullable=True))
    op.execute("UPDATE events SET winning_mode = 'AUDIENCE_VOTE' WHERE winning_mode IS NULL")
    op.alter_column('events', 'winning_mode', nullable=False)

    op.add_column('stage_results', sa.Column('judge_score_total', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stage_results', 'judge_score_total')
    op.drop_column('events', 'winning_mode')
    sa.Enum(name='winningmode').drop(op.get_bind())
    op.drop_index(op.f('ix_judge_scores_submission_id'), table_name='judge_scores')
    op.drop_index(op.f('ix_judge_scores_judge_id'), table_name='judge_scores')
    op.drop_table('judge_scores')
    op.drop_index(op.f('ix_event_judges_user_id'), table_name='event_judges')
    op.drop_index(op.f('ix_event_judges_event_id'), table_name='event_judges')
    op.drop_table('event_judges')
    # ### end Alembic commands ###
