"""add site settings table

Revision ID: b6c687f441f9
Revises: d4a96917e1f4
Create Date: 2026-08-11 00:16:10.262344

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'b6c687f441f9'
down_revision = 'd4a96917e1f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('welcome_credit_amount', sa.Integer(), nullable=False),
    sa.Column('max_upload_size_mb', sa.Integer(), nullable=False),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_settings')
    # ### end Alembic commands ###
